{
  # data
  'driving_path': './data/driving/driving1.mp4',
  'save_path': './res/vid_edit/',
  # model setting
  'ckpt_path': './model/lia-x.pt',
  'size': 512, # resolution
  'motion_dim': 40,
  'scale': 2,
  # motion dictionary setting
  'motion_id': [
    37, # yaw1
    39, # yaw2
    28, # pitch
    15, # roll1
    33, # roll2
    31, # neck
    6,  # pout
    25, # open->close mouth
    16, # 'O' mouth
    19, # moving apple cheek
    13, # close->open eyes
    24, # raise/frown eyebrows
    17, # moving eyeballs1
    26, # moving eyeballs2
  ],
  'motion_value': [
      0.5, # 37
      0.5, # 39
      0, # 28
      0, # 15
      0, # 33
      0, # 31
      0, # 6
      0, # 25
      0, # 16
      0, # 19
      0, # 13
      0, # 24
      0, # 17
      0  # 26
  ]
}
