{
  # data
  'source_path': './data/source/portrait1.png',
  'driving_path': './data/driving/driving1.mp4',
  'save_path': './res/animation/',
  # model setting
  'ckpt_path': './model/lia-x.pt',
  'size': 512, # resolution
  'motion_dim': 40,
  'scale': 2,
  # motion dictionary setting
  'motion_id': [
    37, # yaw1
    39, # yaw2
    28, # pitch
    15, # roll1
    33, # roll2
    31, # neck
    6,  # pout
    25, # open->close mouth
    16, # 'O' mouth
    19, # moving apple cheek
    13, # close->open eyes
    24, # raise/frown eyebrows
    17, # moving eyeballs1
    26, # moving eyeballs2
  ],
  'motion_value': [
      -0.03, # 37
      0.21, # 39
      -0.31, # 28
      -0.12, # 15
      -0.11, # 33
      0, # 31
      -0.1, # 6
      -0.12, # 25
      0, # 16
      0.11, # 19
      0, # 13
      0, # 24
      -0.02, # 17
      0.07  # 26
  ]
}
